/* ReliefLink - Active Worldwide Disasters panel backed by live public feeds. */
(function(){
  'use strict';
  const USGS='https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php?format=geojson&feed=all_hour';
  const EONET='https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&days=7&limit=100';
  let currentMap=null, timer=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const coords=g=>{if(!g||!Array.isArray(g.coordinates))return null;if(g.type==='Point'){const a=Number(g.coordinates[1]),b=Number(g.coordinates[0]);return Number.isFinite(a)&&Number.isFinite(b)?[a,b]:null}const pts=[];(function w(v){if(Array.isArray(v)){if(typeof v[0]==='number'&&typeof v[1]==='number')pts.push(v);else v.forEach(w)}})(g.coordinates);if(!pts.length)return null;return [pts.reduce((s,p)=>s+Number(p[1]),0)/pts.length,pts.reduce((s,p)=>s+Number(p[0]),0)/pts.length]};
  function ensureStyle(){if(document.getElementById('rl-world-panel-style'))return;const s=document.createElement('style');s.id='rl-world-panel-style';s.textContent=`#rl-active-incidents{position:absolute!important;top:14px!important;right:14px!important;bottom:auto!important;width:min(350px,calc(100% - 28px))!important;max-height:calc(100% - 28px)!important;z-index:1000!important;background:rgba(255,255,255,.97)!important;border:1px solid rgba(148,163,184,.3)!important;border-radius:12px!important;box-shadow:0 10px 32px rgba(15,23,42,.24)!important;overflow:hidden!important;font-family:Inter,system-ui,sans-serif!important}.rl-world-head{display:flex;align-items:center;justify-content:space-between;padding:14px 15px;border-bottom:1px solid #e5e7eb}.rl-world-title{font-size:.86rem;font-weight:800;color:#111827}.rl-world-live{font-size:.68rem;font-weight:700;color:#16a34a}.rl-world-list{max-height:430px;overflow:auto;padding:8px}.rl-world-card{display:block;width:100%;text-align:left;padding:11px;margin:0 0 7px;border:1px solid #e5e7eb;border-left:4px solid #64748b;border-radius:9px;background:#fff;cursor:pointer}.rl-world-card:hover{background:#f8fafc}.rl-world-name{font-size:.78rem;font-weight:800;color:#111827;line-height:1.25}.rl-world-meta{font-size:.67rem;color:#64748b;margin-top:3px}.rl-world-row{display:flex;justify-content:space-between;gap:8px;margin-top:6px;font-size:.66rem;color:#475569}.rl-world-source{font-size:.6rem;color:#94a3b8;margin-top:6px}.rl-world-empty{padding:18px 12px;text-align:center;color:#64748b;font-size:.75rem}.rl-world-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px}`;document.head.appendChild(s)}
  async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(r.status);return r.json()}
  async function refresh(map){if(!map)return;ensureStyle();let p=document.getElementById('rl-active-incidents');if(!p)return;const head=`<div class="rl-world-head"><span class="rl-world-title">Active Worldwide Disasters</span><span class="rl-world-live">● LIVE</span></div>`;p.innerHTML=head+'<div class="rl-world-list"><div class="rl-world-empty">Refreshing verified public feeds…</div></div>';let eq=[],eo=[];const r=await Promise.allSettled([json(USGS),json(EONET)]);if(r[0].status==='fulfilled')eq=Array.isArray(r[0].value.features)?r[0].value.features:[];if(r[1].status==='fulfilled')eo=Array.isArray(r[1].value.features)?r[1].value.features:[];const items=[];eq.forEach(f=>{const c=coords(f.geometry);if(!c)return;const x=f.properties||{},m=Number(x.mag);items.push({coords:c,title:`Earthquake ${Number.isFinite(m)?'M'+m.toFixed(1):''}`,place:x.place||'Unknown location',detail:`Depth: ${f.geometry.coordinates.length>2&&Number.isFinite(Number(f.geometry.coordinates[2]))?Number(f.geometry.coordinates[2])+' km':'Data unavailable'} · Tsunami: ${x.tsunami===1?'Yes':x.tsunami===0?'No':'Data unavailable'}`,time:x.time?new Date(x.time).toLocaleString():'Unknown time',source:'USGS',color:m>=6?'#dc2626':m>=4.5?'#f59e0b':'#eab308'});});eo.forEach(f=>{const c=coords(f.geometry);if(!c)return;const x=f.properties||{},cat=Array.isArray(x.categories)?x.categories.map(v=>v.title||v).join(', '):'Natural event';items.push({coords:c,title:x.title||'Natural event',place:cat,detail:`Magnitude: ${x.magnitudeValue!==undefined?String(x.magnitudeValue)+' '+(x.magnitudeUnit||''):'Data unavailable'}`,time:x.date?new Date(x.date).toLocaleString():'Unknown time',source:'NASA EONET',color:'#7c3aed'});});items.sort((a,b)=>a.time<b.time?1:-1);const list=p.querySelector('.rl-world-list');if(!items.length){list.innerHTML='<div class="rl-world-empty">No verified public events available right now.</div>';return}list.innerHTML=items.slice(0,10).map((x,i)=>`<button class="rl-world-card" data-i="${i}" style="border-left-color:${x.color}"><div class="rl-world-name"><span class="rl-world-dot" style="background:${x.color}"></span>${esc(x.title)}</div><div class="rl-world-meta">${esc(x.place)}</div><div class="rl-world-row"><span>${esc(x.detail)}</span><span>${esc(x.time)}</span></div><div class="rl-world-source">Source: ${esc(x.source)}</div></button>`).join('');list.querySelectorAll('.rl-world-card').forEach((b,i)=>b.onclick=()=>{const x=items[i];if(x&&x.coords){map.flyTo(x.coords,Math.max(map.getZoom(),5),{duration:.5})}})}
  function attach(){const map=window.__reliefLinkActiveMap;if(!map||!window.L||currentMap===map)return;currentMap=map;clearInterval(timer);refresh(map);timer=setInterval(()=>refresh(map),60000)}
  setInterval(attach,500);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach);else attach();
})();
