/* ReliefLink 3D Earth v3 */
(function(){'use strict';
const U='https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_hour.geojson',N='https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&days=7';
let v=null,h=null,t=null,busy=false;
const esc=x=>String(x??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const status=x=>{const e=document.querySelector('#live-data-status');if(e)e.textContent=x};
const count=(id,n)=>{const e=document.querySelector(id);if(e)e.textContent=n+' active'};
function prepare(m){if(!m)return null;m.classList.add('relieflink-3d-host');m.style.cssText+=';position:relative!important;overflow:hidden!important;background:#02050a!important';let g=m.querySelector('#relieflink-3d-earth');if(!g){g=document.createElement('div');g.id='relieflink-3d-earth';g.setAttribute('aria-label','ReliefLink interactive 3D Earth');m.appendChild(g)}g.style.cssText='position:absolute!important;inset:0!important;width:100%!important;height:100%!important;z-index:20!important;display:block!important;visibility:visible!important;background:#02050a!important;overflow:hidden!important';const l=m.querySelector('.leaflet-container');if(l){l.style.setProperty('display','none','important');l.style.setProperty('visibility','hidden','important');l.style.setProperty('pointer-events','none','important')}return g}
function create(g){if(!window.Cesium||!g)return null;try{const p=new Cesium.UrlTemplateImageryProvider({url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',maximumLevel:19,enablePickFeatures:false,credit:'Esri World Imagery'});const x=new Cesium.Viewer(g,{baseLayerPicker:false,baseLayer:new Cesium.ImageryLayer(p),terrainProvider:new Cesium.EllipsoidTerrainProvider(),animation:false,timeline:false,geocoder:false,homeButton:true,sceneModePicker:true,navigationHelpButton:false,fullscreenButton:false,vrButton:false,shadows:false,scene3DOnly:true,shouldAnimate:false,requestRenderMode:false,selectionIndicator:true,infoBox:true});x.scene.globe.show=true;x.scene.globe.enableLighting=true;x.scene.globe.showGroundAtmosphere=true;x.scene.skyAtmosphere.show=true;x.scene.backgroundColor=Cesium.Color.BLACK;x.resolutionScale=Math.min(window.devicePixelRatio||1,1.5);const target=Cesium.Cartesian3.fromDegrees(78,18,0);x.camera.lookAt(target,new Cesium.HeadingPitchRange(0,Cesium.Math.toRadians(-70),12000000));x.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);x.scene.requestRender();return x}catch(e){console.error('3D Earth init:',e);status('3D Earth initialization failed');return null}}
function eq(f){const g=f.geometry,p=f.properties||{},c=g&&g.coordinates;if(!Array.isArray(c))return false;const lng=+c[0],lat=+c[1],mag=+p.mag;if(!Number.isFinite(lng)||!Number.isFinite(lat))return false;const col=mag>=6?'#ff3b30':mag>=5?'#ff9500':'#ffd60a';v.entities.add({position:Cesium.Cartesian3.fromDegrees(lng,lat,18000),point:{pixelSize:Number.isFinite(mag)?Math.max(8,Math.min(20,7+mag*1.7)):10,color:Cesium.Color.fromCssColorString(col),outlineColor:Cesium.Color.WHITE,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY},label:{text:'M'+(Number.isFinite(mag)?mag.toFixed(1):'—'),font:'600 13px Inter,sans-serif',fillColor:Cesium.Color.WHITE,outlineColor:Cesium.Color.BLACK,outlineWidth:3,pixelOffset:new Cesium.Cartesian2(0,-24),showBackground:true,backgroundColor:Cesium.Color.fromAlpha(Cesium.Color.BLACK,.65),disableDepthTestDistance:Number.POSITIVE_INFINITY},description:`<h3 style="color:${col}">Live Earthquake · M${Number.isFinite(mag)?mag.toFixed(1):'—'}</h3><p><b>Location:</b> ${esc(p.place||'Unknown')}</p><p><b>Depth:</b> ${Number.isFinite(+c[2])?(+c[2]).toFixed(1)+' km':'—'}</p><p><b>Time:</b> ${p.time?esc(new Date(p.time).toLocaleString()):'Unknown'}</p><small>Source: USGS</small>`});return true}
function nasa(f){const g=f.geometry,p=f.properties||{};if(!g||g.type!=='Point'||!Array.isArray(g.coordinates))return false;const lng=+g.coordinates[0],lat=+g.coordinates[1];if(!Number.isFinite(lng)||!Number.isFinite(lat))return false;v.entities.add({position:Cesium.Cartesian3.fromDegrees(lng,lat,12000),point:{pixelSize:9,color:Cesium.Color.fromCssColorString('#9b7cff'),outlineColor:Cesium.Color.WHITE,outlineWidth:2,disableDepthTestDistance:Number.POSITIVE_INFINITY},description:`<h3 style="color:#9b7cff">${esc(p.title||'NASA natural event')}</h3><p><b>Reported:</b> ${p.date?esc(new Date(p.date).toLocaleString()):'Unknown'}</p><small>Source: NASA EONET</small>`});return true}
async function refresh(){if(!v||v.isDestroyed()||busy)return;busy=true;try{const[a,b]=await Promise.all([fetch(U,{cache:'no-store'}),fetch(N,{cache:'no-store'})]);if(!a.ok||!b.ok)throw Error('feed');const[A,B]=await Promise.all([a.json(),b.json()]);v.entities.removeAll();let q=0,n=0;(A.features||[]).forEach(f=>{if(eq(f))q++});for(const f of(B.features||[])){if(n>=80)break;if(nasa(f))n++}count('#earthquake-count',q);count('#eonet-count',n);status(`3D Earth • USGS: ${q} earthquakes • NASA: ${n} events • Updated ${new Date().toLocaleTimeString()}`);v.scene.requestRender()}catch(e){console.warn('3D feeds:',e);status('3D Earth • Live feeds temporarily unavailable')}finally{busy=false}}
function destroy(){if(t){clearInterval(t);t=null}if(v&&!v.isDestroyed())v.destroy();v=null;h=null}
function ensure(){const m=document.querySelector('#disaster-map-element');if(!m||!window.Cesium){if(!m&&v)destroy();return}prepare(m);if(h!==m||!v||v.isDestroyed()){destroy();h=m;v=create(prepare(m));if(!v)return;prepare(m);refresh();t=setInterval(refresh,60000)}}
function start(){if(!document.getElementById('relieflink-3d-earth-style')){const s=document.createElement('style');s.id='relieflink-3d-earth-style';s.textContent='#relieflink-3d-earth .cesium-widget,#relieflink-3d-earth .cesium-widget canvas{width:100%!important;height:100%!important;display:block!important}#relieflink-3d-earth .cesium-viewer-toolbar{top:10px;right:10px}';document.head.appendChild(s)}ensure();new MutationObserver(ensure).observe(document.body,{childList:true,subtree:true});addEventListener('resize',()=>{if(v&&!v.isDestroyed())v.resize()});window.ReliefLink3DEarth={refresh,getViewer:()=>v};setInterval(ensure,1000)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start,{once:true}):start();})();