/* ReliefLink - Live Disaster Data
 * Official USGS earthquakes + NASA EONET events.
 * Uses Leaflet circle markers so geographic positions remain stable during zoom/pan.
 */
(function(){'use strict';
const USGS_URL='https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php?format=geojson&feed=all_hour';
const EONET_URL='https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&days=7';
const REFRESH_MS=60000,MAX_EARTHQUAKES=100,MAX_EONET=100;
let liveMap=null,liveEarthquakes=null,liveEonet=null,refreshTimer=null,refreshQueued=false,isInteracting=false,requestInFlight=false;
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sev=mag=>mag>=6?{label:'critical',color:'#EF4444'}:mag>=4.5?{label:'high',color:'#F59E0B'}:mag>=2.5?{label:'medium',color:'#EAB308'}:{label:'low',color:'#22C55E'};
function point(f){const g=f&&f.geometry;if(!g||g.type!=='Point'||!Array.isArray(g.coordinates))return null;const lng=Number(g.coordinates[0]),lat=Number(g.coordinates[1]);return Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng]:null;}
function status(t){const el=document.querySelector('#live-data-status');if(el)el.textContent=t;const s=document.querySelector('#rl-live-status');if(s)s.innerHTML='<span class="rl-live-dot"></span><b>LIVE</b> · '+safe(t.replace(/^Live feeds\s*•\s*/i,''));}
function bind(map){if(map.__reliefLinkLiveInteractionBound)return;map.__reliefLinkLiveInteractionBound=true;map.on('zoomstart movestart',()=>isInteracting=true);map.on('zoomend moveend',()=>{isInteracting=false;if(refreshQueued){refreshQueued=false;setTimeout(()=>refresh(map),250)}})}
function panel(map){let p=document.getElementById('rl-active-incidents');if(p)return p;const host=map.getContainer();p=document.createElement('aside');p.id='rl-active-incidents';p.innerHTML='<div class="rl-ai-head"><strong>ACTIVE INCIDENTS</strong><span class="rl-ai-count">Loading…</span></div><div class="rl-ai-list"></div>';host.appendChild(p);return p;}
function renderPanel(map,items){const p=panel(map),list=p.querySelector('.rl-ai-list'),count=p.querySelector('.rl-ai-count');count.textContent=`${items.length} live`;list.innerHTML=items.slice(0,8).map((x,i)=>`<button class="rl-ai-item" data-index="${i}"><span class="rl-ai-dot" style="background:${x.color}"></span><span><b>${safe(x.title)}</b><small>${safe(x.meta)}</small></span></button>`).join('');list.querySelectorAll('.rl-ai-item').forEach((b,i)=>b.onclick=()=>{const x=items[i];if(x.coords){map.flyTo(x.coords,Math.max(map.getZoom(),5),{duration:.55});if(x.layer) x.layer.openPopup()}});}
function ensureStyle(){if(document.getElementById('rl-active-incident-style'))return;const s=document.createElement('style');s.id='rl-active-incident-style';s.textContent=`#rl-active-incidents{position:absolute;right:12px;bottom:12px;z-index:1000;width:min(330px,calc(100% - 24px));max-height:45%;overflow:hidden;background:rgba(255,255,255,.96);backdrop-filter:blur(8px);border:1px solid rgba(100,116,139,.2);border-radius:12px;box-shadow:0 8px 28px rgba(15,23,42,.18);font-family:Inter,sans-serif}.rl-ai-head{display:flex;justify-content:space-between;align-items:center;padding:11px 13px;border-bottom:1px solid rgba(100,116,139,.16);font-size:.72rem;letter-spacing:.04em}.rl-ai-count{font-size:.68rem;color:#64748b}.rl-ai-list{max-height:220px;overflow:auto;padding:6px}.rl-ai-item{width:100%;display:flex;align-items:flex-start;gap:9px;text-align:left;border:0;background:transparent;padding:9px;border-radius:8px;cursor:pointer}.rl-ai-item:hover{background:rgba(59,130,246,.07)}.rl-ai-dot{flex:0 0 9px;width:9px;height:9px;border-radius:50%;margin-top:4px;box-shadow:0 0 0 4px rgba(100,116,139,.08)}.rl-ai-item b{display:block;font-size:.73rem;line-height:1.25;color:#0f172a}.rl-ai-item small{display:block;margin-top:3px;font-size:.64rem;color:#64748b}.rl-ai-item{transition:transform .16s ease}.rl-ai-item:hover{transform:translateX(3px)}`;document.head.appendChild(s)}
async function refresh(map){if(!map||!window.L||requestInFlight)return;if(isInteracting){refreshQueued=true;return}requestInFlight=true;try{const [er,nr]=await Promise.all([fetch(USGS_URL,{cache:'no-store'}),fetch(EONET_URL,{cache:'no-store'})]);if(!er.ok||!nr.ok)throw new Error('live feed unavailable');const [eq,no]=await Promise.all([er.json(),nr.json()]);const nextEq=L.layerGroup(),nextNo=L.layerGroup(),items=[];
const earthquakes=Array.isArray(eq.features)?eq.features.slice(0,MAX_EARTHQUAKES):[];earthquakes.forEach(f=>{const coords=point(f);if(!coords)return;const p=f.properties||{},mag=Number(p.mag),s=sev(Number.isFinite(mag)?mag:0),depth=f.geometry.coordinates.length>2?Number(f.geometry.coordinates[2]):null,place=safe(p.place||'Unknown location'),when=p.time?new Date(p.time).toLocaleString():'Unknown time';const layer=L.circleMarker(coords,{radius:Math.max(4,Math.min(11,4+(Number.isFinite(mag)?mag*.8:0))),color:s.color,weight:2,fillColor:s.color,fillOpacity:.78,className:'rl-live-earthquake-circle'}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:270px"><h4 style="margin:0 0 6px;color:${s.color}">Live Earthquake · M${Number.isFinite(mag)?mag.toFixed(1):'—'}</h4><p style="margin:0 0 4px"><b>Location:</b> ${place}</p><p style="margin:0 0 4px"><b>Severity:</b> ${s.label}</p><p style="margin:0 0 4px"><b>Depth:</b> ${Number.isFinite(depth)?depth+' km':'Data unavailable'}</p><p style="margin:0 0 4px"><b>Tsunami flag:</b> ${p.tsunami===1?'Yes':p.tsunami===0?'No':'Data unavailable'}</p><p style="margin:0"><b>Time:</b> ${safe(when)}</p><p style="margin:7px 0 0;font-size:.7rem">Source: USGS</p></div>`).addTo(nextEq);items.push({title:`Earthquake M${Number.isFinite(mag)?mag.toFixed(1):'—'}`,meta:place,coords,layer,color:s.color});});
const events=Array.isArray(no.features)?no.features.slice(0,MAX_EONET):[];events.forEach(f=>{const coords=point(f);if(!coords)return;const p=f.properties||{},title=p.title||'Natural event',cat=Array.isArray(p.categories)?p.categories.map(c=>c.title||c).join(', '):'Natural event',date=p.date?new Date(p.date).toLocaleString():'Unknown date';const layer=L.circleMarker(coords,{radius:5,color:'#7C3AED',weight:2,fillColor:'#7C3AED',fillOpacity:.78,className:'rl-live-eonet-circle'}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:270px"><h4 style="margin:0 0 6px;color:#6D28D9">${safe(title)}</h4><p style="margin:0 0 4px"><b>Category:</b> ${safe(cat)}</p><p style="margin:0 0 4px"><b>Reported:</b> ${safe(date)}</p><p style="margin:0 0 4px"><b>Impact:</b> Data unavailable</p><p style="margin:7px 0 0;font-size:.7rem">Source: NASA EONET</p></div>`).addTo(nextNo);items.push({title,meta:cat,coords,layer,color:'#7C3AED'});});
if(liveEarthquakes&&map.hasLayer(liveEarthquakes))map.removeLayer(liveEarthquakes);if(liveEonet&&map.hasLayer(liveEonet))map.removeLayer(liveEonet);liveEarthquakes=nextEq;liveEonet=nextNo;if(!isInteracting){liveEarthquakes.addTo(map);liveEonet.addTo(map)}else refreshQueued=true;ensureStyle();renderPanel(map,items);
const e=document.querySelector('#earthquake-count'),n=document.querySelector('#eonet-count');if(e)e.textContent=`${earthquakes.length} active`;if(n)n.textContent=`${items.length-earthquakes.length} active`;status(`USGS: ${earthquakes.length} earthquakes • NASA: ${items.length-earthquakes.length} events • Updated ${new Date().toLocaleTimeString()}`);
}catch(err){console.warn('Live disaster feed refresh failed:',err);status('Unable to refresh public disaster feeds right now')}finally{requestInFlight=false}}
function attach(){const map=window.__reliefLinkActiveMap;if(!map||!window.L||liveMap===map)return;liveMap=map;bind(map);refresh(map);if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>refresh(liveMap),REFRESH_MS)}
setInterval(attach,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach);else attach();
})();
