/* ReliefLink - Live Disaster Data
 * Official USGS earthquakes + NASA EONET events.
 * Each source is handled independently so one unavailable feed cannot hide the others.
 */
(function(){'use strict';
const USGS_URL='https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php?format=geojson&feed=all_hour';
const EONET_URL='https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&days=7&limit=100';
const REFRESH_MS=60000,MAX_EARTHQUAKES=100,MAX_EONET=100;
let liveMap=null,liveEarthquakes=null,liveEonet=null,refreshTimer=null,refreshQueued=false,isInteracting=false,requestInFlight=false;
const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const sev=mag=>mag>=6?{label:'critical',color:'#EF4444'}:mag>=4.5?{label:'high',color:'#F59E0B'}:mag>=2.5?{label:'medium',color:'#EAB308'}:{label:'low',color:'#22C55E'};
function coordsForGeometry(g){
  if(!g||!Array.isArray(g.coordinates))return null;
  if(g.type==='Point'){const lng=Number(g.coordinates[0]),lat=Number(g.coordinates[1]);return Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng]:null}
  const flat=[];(function walk(v){if(Array.isArray(v)){if(v.length>=2&&typeof v[0]==='number'&&typeof v[1]==='number')flat.push(v);else v.forEach(walk)}})(g.coordinates);
  if(!flat.length)return null;const sum=flat.reduce((a,c)=>{a[0]+=Number(c[1]);a[1]+=Number(c[0]);return a},[0,0]);return [sum[0]/flat.length,sum[1]/flat.length]
}
function status(t){const el=document.querySelector('#live-data-status');if(el)el.textContent=t;const s=document.querySelector('#rl-live-status');if(s)s.remove()}
function bind(map){if(map.__reliefLinkLiveInteractionBound)return;map.__reliefLinkLiveInteractionBound=true;map.on('zoomstart movestart',()=>isInteracting=true);map.on('zoomend moveend',()=>{isInteracting=false;if(refreshQueued){refreshQueued=false;setTimeout(()=>refresh(map),250)}})}
function panel(map){let p=document.getElementById('rl-active-incidents');if(p)return p;const host=map.getContainer();p=document.createElement('aside');p.id='rl-active-incidents';p.innerHTML='<div class="rl-ai-head"><strong>ACTIVE INCIDENTS</strong><span class="rl-ai-count">Loading…</span></div><div class="rl-ai-list"></div>';host.appendChild(p);return p}
function renderPanel(map,items){const p=panel(map),list=p.querySelector('.rl-ai-list'),count=p.querySelector('.rl-ai-count');count.textContent=`${items.length} live`;list.innerHTML=items.slice(0,8).map((x,i)=>`<button class="rl-ai-item" data-index="${i}"><span class="rl-ai-dot" style="background:${x.color}"></span><span><b>${safe(x.title)}</b><small>${safe(x.meta)}</small></span></button>`).join('');list.querySelectorAll('.rl-ai-item').forEach((b,i)=>b.onclick=()=>{const x=items[i];if(x.coords){map.flyTo(x.coords,Math.max(map.getZoom(),5),{duration:.55});setTimeout(()=>x.layer&&x.layer.openPopup(),600)}})}
function ensureStyle(){if(document.getElementById('rl-active-incident-style'))return;const s=document.createElement('style');s.id='rl-active-incident-style';s.textContent=`#rl-active-incidents{position:absolute;right:12px;bottom:12px;z-index:900;width:min(330px,calc(100% - 24px));max-height:45%;overflow:hidden;background:rgba(255,255,255,.96);backdrop-filter:blur(8px);border:1px solid rgba(100,116,139,.2);border-radius:12px;box-shadow:0 8px 28px rgba(15,23,42,.18);font-family:Inter,sans-serif}.rl-ai-head{display:flex;justify-content:space-between;align-items:center;padding:11px 13px;border-bottom:1px solid rgba(100,116,139,.16);font-size:.72rem;letter-spacing:.04em}.rl-ai-count{font-size:.68rem;color:#64748b}.rl-ai-list{max-height:220px;overflow:auto;padding:6px}.rl-ai-item{width:100%;display:flex;align-items:flex-start;gap:9px;text-align:left;border:0;background:transparent;padding:9px;border-radius:8px;cursor:pointer}.rl-ai-item:hover{background:rgba(59,130,246,.07)}.rl-ai-dot{flex:0 0 9px;width:9px;height:9px;border-radius:50%;margin-top:4px}.rl-ai-item b{display:block;font-size:.73rem;line-height:1.25;color:#0f172a}.rl-ai-item small{display:block;margin-top:3px;font-size:.64rem;color:#64748b}.rl-ai-item{transition:transform .16s ease}.rl-ai-item:hover{transform:translateX(3px)}`;document.head.appendChild(s)}
async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
async function refresh(map){if(!map||!window.L||requestInFlight)return;if(isInteracting){refreshQueued=true;return}requestInFlight=true;try{
  const [eqResult,eonetResult]=await Promise.allSettled([getJson(USGS_URL),getJson(EONET_URL)]);
  const nextEq=L.layerGroup(),nextNo=L.layerGroup(),items=[],earthquakes=eqResult.status==='fulfilled'&&Array.isArray(eqResult.value.features)?eqResult.value.features.slice(0,MAX_EARTHQUAKES):[],events=eonetResult.status==='fulfilled'&&Array.isArray(eonetResult.value.features)?eonetResult.value.features.slice(0,MAX_EONET):[];
  earthquakes.forEach(f=>{const coords=coordsForGeometry(f.geometry);if(!coords)return;const p=f.properties||{},mag=Number(p.mag),s=sev(Number.isFinite(mag)?mag:0),depth=f.geometry.coordinates.length>2?Number(f.geometry.coordinates[2]):null,place=safe(p.place||'Unknown location'),when=p.time?new Date(p.time).toLocaleString():'Unknown time';const layer=L.circleMarker(coords,{radius:Math.max(4,Math.min(11,4+(Number.isFinite(mag)?mag*.8:0))),color:s.color,weight:2,fillColor:s.color,fillOpacity:.78,className:'rl-live-earthquake-circle'}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:270px"><h4 style="margin:0 0 6px;color:${s.color}">Live Earthquake · M${Number.isFinite(mag)?mag.toFixed(1):'—'}</h4><p style="margin:0 0 4px"><b>Location:</b> ${place}</p><p style="margin:0 0 4px"><b>Severity:</b> ${s.label}</p><p style="margin:0 0 4px"><b>Depth:</b> ${Number.isFinite(depth)?depth+' km':'Data unavailable'}</p><p style="margin:0 0 4px"><b>Tsunami flag:</b> ${p.tsunami===1?'Yes':p.tsunami===0?'No':'Data unavailable'}</p><p style="margin:0"><b>Time:</b> ${safe(when)}</p><p style="margin:7px 0 0;font-size:.7rem">Source: USGS</p></div>`).addTo(nextEq);items.push({title:`Earthquake M${Number.isFinite(mag)?mag.toFixed(1):'—'}`,meta:place,coords,layer,color:s.color});});
  events.forEach(f=>{const coords=coordsForGeometry(f.geometry);if(!coords)return;const p=f.properties||{},title=p.title||'Natural event',cat=Array.isArray(p.categories)?p.categories.map(c=>c.title||c).join(', '):'Natural event',date=p.date?new Date(p.date).toLocaleString():'Unknown date',mag=p.magnitudeValue!==undefined?`${p.magnitudeValue} ${p.magnitudeUnit||''}`.trim():'Data unavailable';const layer=L.circleMarker(coords,{radius:6,color:'#7C3AED',weight:2,fillColor:'#7C3AED',fillOpacity:.78,className:'rl-live-eonet-circle'}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:290px"><h4 style="margin:0 0 6px;color:#6D28D9">${safe(title)}</h4><p style="margin:0 0 4px"><b>Category:</b> ${safe(cat)}</p><p style="margin:0 0 4px"><b>Magnitude:</b> ${safe(mag)}</p><p style="margin:0 0 4px"><b>Reported:</b> ${safe(date)}</p><p style="margin:0 0 4px"><b>Impact:</b> Data unavailable</p><p style="margin:7px 0 0;font-size:.7rem">Source: NASA EONET</p></div>`).addTo(nextNo);items.push({title,meta:cat,coords,layer,color:'#7C3AED'});});
  if(liveEarthquakes&&map.hasLayer(liveEarthquakes))map.removeLayer(liveEarthquakes);if(liveEonet&&map.hasLayer(liveEonet))map.removeLayer(liveEonet);liveEarthquakes=nextEq;liveEonet=nextNo;liveEarthquakes.addTo(map);liveEonet.addTo(map);ensureStyle();renderPanel(map,items);
  const e=document.querySelector('#earthquake-count'),n=document.querySelector('#eonet-count');if(e)e.textContent=`${earthquakes.length} active`;if(n)n.textContent=`${events.length} active`;
  const usgsOk=eqResult.status==='fulfilled',eonetOk=eonetResult.status==='fulfilled';status(`USGS ${usgsOk?'✓':'×'} ${earthquakes.length} • NASA ${eonetOk?'✓':'×'} ${events.length}`);
}catch(err){console.warn('Live disaster feed refresh failed:',err);status('Live disaster feeds unavailable')}finally{requestInFlight=false}}
function attach(){const map=window.__reliefLinkActiveMap;if(!map||!window.L||liveMap===map)return;liveMap=map;bind(map);refresh(map);if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>refresh(liveMap),REFRESH_MS)}
setInterval(attach,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach);else attach();
})();
