/* ReliefLink - Live Disaster Data
 * Official USGS earthquakes + NASA EONET events.
 * Marker visuals use lightweight Leaflet div icons so CSS pulse animation is visible.
 */
(function () {
  'use strict';
  const USGS_URL='https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php?format=geojson&feed=all_hour';
  const EONET_URL='https://eonet.gsfc.nasa.gov/api/v3/events/geojson?status=open&days=7';
  const REFRESH_MS=60000, MAX_EARTHQUAKES=100, MAX_EONET=100;
  let liveMap=null,liveEarthquakes=null,liveEonet=null,refreshTimer=null,refreshQueued=false,isInteracting=false,requestInFlight=false;
  const safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const severityForMagnitude=mag=>mag>=6?{label:'critical',color:'#EF4444'}:mag>=4.5?{label:'high',color:'#F59E0B'}:mag>=2.5?{label:'medium',color:'#EAB308'}:{label:'low',color:'#22C55E'};
  function status(t){const el=document.querySelector('#live-data-status');if(el)el.textContent=t;const s=document.querySelector('#rl-live-status');if(s)s.innerHTML='<span class="rl-live-dot"></span><b>LIVE</b> · '+safe(t.replace(/^Live feeds\s*•\s*/i,''));}
  function point(f){const g=f&&f.geometry;if(!g||g.type!=='Point'||!Array.isArray(g.coordinates))return null;const lng=Number(g.coordinates[0]),lat=Number(g.coordinates[1]);return Number.isFinite(lat)&&Number.isFinite(lng)?[lat,lng]:null;}
  function markerIcon(color,label,critical){return window.L.divIcon({className:'rl-disaster-marker-host',iconSize:[22,22],iconAnchor:[11,11],html:`<span class="rl-disaster-marker ${critical?'critical':''}" style="--rl-marker-color:${color}" aria-label="${safe(label)}"><i></i></span>`});}
  function bindInteraction(map){if(!map||map.__reliefLinkLiveInteractionBound)return;map.__reliefLinkLiveInteractionBound=true;map.on('zoomstart movestart',()=>{isInteracting=true;});map.on('zoomend moveend',()=>{isInteracting=false;if(refreshQueued){refreshQueued=false;setTimeout(()=>refresh(map),250);}});}
  async function refresh(map){if(!map||!window.L||requestInFlight)return;if(isInteracting){refreshQueued=true;return;}requestInFlight=true;try{
    const [er,nr]=await Promise.all([fetch(USGS_URL,{cache:'no-store'}),fetch(EONET_URL,{cache:'no-store'})]);if(!er.ok)throw new Error(`USGS ${er.status}`);if(!nr.ok)throw new Error(`NASA EONET ${nr.status}`);const [eqData,noData]=await Promise.all([er.json(),nr.json()]);
    const nextEq=window.L.layerGroup(),nextNo=window.L.layerGroup();
    const earthquakes=Array.isArray(eqData.features)?eqData.features.slice(0,MAX_EARTHQUAKES):[];
    earthquakes.forEach(f=>{const coords=point(f);if(!coords)return;const p=f.properties||{},mag=Number(p.mag),sev=severityForMagnitude(Number.isFinite(mag)?mag:0),place=safe(p.place||'Unknown location'),when=p.time?new Date(p.time).toLocaleString():'Unknown time',depth=f.geometry.coordinates.length>2?Number(f.geometry.coordinates[2]):null;window.L.marker(coords,{icon:markerIcon(sev.color,'Live earthquake',sev.label==='critical'),keyboard:true}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:250px"><h4 style="margin:0 0 5px;color:${sev.color}">Live Earthquake · M${Number.isFinite(mag)?mag.toFixed(1):'—'}</h4><p style="margin:0 0 4px;font-size:.8rem"><strong>Location:</strong> ${place}</p><p style="margin:0 0 4px;font-size:.8rem"><strong>Severity:</strong> ${sev.label}</p><p style="margin:0 0 4px;font-size:.8rem"><strong>Time:</strong> ${safe(when)}</p><p style="margin:0;font-size:.78rem"><strong>Depth:</strong> ${Number.isFinite(depth)?depth+' km':'—'}</p><p style="margin:6px 0 0;font-size:.72rem">Source: USGS Earthquake Hazards Program</p></div>`).addTo(nextEq);});
    const events=Array.isArray(noData.features)?noData.features.slice(0,MAX_EONET):[];let count=0;events.forEach(f=>{const coords=point(f);if(!coords)return;count++;const p=f.properties||{},title=safe(p.title||'NASA natural event'),cat=safe(Array.isArray(p.categories)?p.categories.map(c=>c.title||c).join(', '):(p.categories||'Natural event')),date=p.date?new Date(p.date).toLocaleString():'Unknown date';window.L.marker(coords,{icon:markerIcon('#7C3AED',title,false)}).bindPopup(`<div style="color:#111;font-family:sans-serif;max-width:250px"><h4 style="margin:0 0 5px;color:#6D28D9">${title}</h4><p style="margin:0 0 4px;font-size:.8rem"><strong>Category:</strong> ${cat}</p><p style="margin:0;font-size:.8rem"><strong>Reported:</strong> ${safe(date)}</p><p style="margin:6px 0 0;font-size:.72rem">Source: NASA EONET</p></div>`).addTo(nextNo);});
    if(!liveEarthquakes)liveEarthquakes=window.L.layerGroup();if(!liveEonet)liveEonet=window.L.layerGroup();if(map.hasLayer(liveEarthquakes))map.removeLayer(liveEarthquakes);if(map.hasLayer(liveEonet))map.removeLayer(liveEonet);liveEarthquakes=nextEq;liveEonet=nextNo;if(!isInteracting){liveEarthquakes.addTo(map);liveEonet.addTo(map);}else refreshQueued=true;
    const eqEl=document.querySelector('#earthquake-count'),noEl=document.querySelector('#eonet-count');if(eqEl)eqEl.textContent=`${earthquakes.length} active`;if(noEl)noEl.textContent=`${count} active`;status(`USGS: ${earthquakes.length} earthquakes • NASA: ${count} events • Updated ${new Date().toLocaleTimeString()}`);
  }catch(e){console.warn('Live disaster feed refresh failed:',e);status('Unable to refresh public disaster feeds right now');}finally{requestInFlight=false;}}
  function attach(){const map=window.__reliefLinkActiveMap;if(!map||!window.L||liveMap===map)return;liveMap=map;bindInteraction(map);refresh(map);if(refreshTimer)clearInterval(refreshTimer);refreshTimer=setInterval(()=>refresh(liveMap),REFRESH_MS);}
  setInterval(attach,1000);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach);else attach();
})();
