/* ReliefLink Animation System v3 - UI animations only. Never transforms or overlays the Leaflet map. */
(function(){'use strict';
const ID='relieflink-animation-system-v3';
function styles(){if(document.getElementById(ID))return;const s=document.createElement('style');s.id=ID;s.textContent=`
:root{--rl-fast:180ms;--rl-motion:260ms}.rl-live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;background:#22c55e;animation:rlPulse 1.8s ease-in-out infinite;vertical-align:middle}.rl-live-dot.offline{background:#ef4444;animation:none}.rl-live-dot.updating{background:#f59e0b}@keyframes rlPulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.38;transform:scale(.78)}}
.rl-page-enter{animation:rlPage .28s cubic-bezier(.2,.7,.2,1) both}.rl-card-enter{animation:rlCard .42s cubic-bezier(.2,.7,.2,1) both}.rl-toast-enter{animation:rlToast .22s ease-out both}.rl-critical-alert{animation:rlAlert .42s cubic-bezier(.2,.7,.2,1) both}@keyframes rlPage{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@keyframes rlCard{from{opacity:0;transform:translateY(9px) scale(.99)}to{opacity:1;transform:none}}@keyframes rlToast{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}@keyframes rlAlert{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:none}}
.rl-live-truth-card{transition:box-shadow .18s ease}.rl-live-truth-card:hover{box-shadow:0 8px 22px rgba(15,23,42,.1)}.rl-notification-new{animation:rlBell .52s ease-in-out}.rl-chart-enter{animation:rlChart .85s ease-out both}.rl-counter{font-variant-numeric:tabular-nums}@keyframes rlBell{0%,100%{transform:rotate(0)}15%{transform:rotate(-8deg)}30%{transform:rotate(8deg)}45%{transform:rotate(-5deg)}60%{transform:rotate(5deg)}}@keyframes rlChart{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
button,.btn,.nav-item,.sidebar-item,a.card,.card,.stat-card,.metric-card{transition:transform .18s ease,box-shadow .18s ease,opacity .18s ease}.nav-item:hover,.sidebar-item:hover{transform:translateX(3px)}button:not(:disabled):active,.btn:not(:disabled):active{transform:scale(.98)}.stat-card:hover,.metric-card:hover{transform:translateY(-2px)}
#disaster-map-element{transform:none!important;will-change:auto!important}.leaflet-container{transform:none!important}.leaflet-map-pane,.leaflet-tile-pane,.leaflet-overlay-pane,.leaflet-shadow-pane,.leaflet-marker-pane,.leaflet-tooltip-pane,.leaflet-popup-pane{will-change:auto!important}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}
`;document.head.appendChild(s)}
function removeMapOverlay(){const e=document.getElementById('rl-live-status');if(e)e.remove()}
function views(){const app=document.querySelector('#app');if(!app)return;let last=null;new MutationObserver(()=>{const a=app.querySelectorAll('main,.main-content,.content-area,.dashboard-content,.view-content,.page-content,.content-panel');const el=a[a.length-1];if(el&&el!==last){last=el;el.classList.remove('rl-page-enter');void el.offsetWidth;el.classList.add('rl-page-enter')}}).observe(app,{childList:true,subtree:true})}
function cards(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('.card,.stat-card,.metric-card,.dashboard-card,.panel').forEach((el,i)=>{if(!el.dataset.rlAnim){el.dataset.rlAnim='1';el.classList.add('rl-card-enter');el.style.animationDelay=Math.min(i*35,280)+'ms'}})).observe(app,{childList:true,subtree:true})}
function counters(){const app=document.querySelector('#app');if(!app)return;const animate=()=>app.querySelectorAll('[data-count],.stat-value,.metric-value,.kpi-value').forEach(el=>{if(el.dataset.rlCounter)return;const m=(el.textContent||'').trim().match(/^(\d[\d,]*)(.*)$/);if(!m)return;const target=Number(m[1].replace(/,/g,''));if(!Number.isFinite(target)||target>10000000)return;el.dataset.rlCounter='1';const suffix=m[2],t0=performance.now();const tick=t=>{const p=Math.min(1,(t-t0)/650),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=v.toLocaleString()+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});animate();new MutationObserver(()=>requestAnimationFrame(animate)).observe(app,{childList:true,subtree:true})}
function charts(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('canvas').forEach(c=>{if(!c.dataset.rlChart){c.dataset.rlChart='1';c.classList.add('rl-chart-enter')}})).observe(app,{childList:true,subtree:true})}
function toasts(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('.toast,.notification,.alert-toast,[role="alert"]').forEach(x=>x.classList.add('rl-toast-enter'))).observe(app,{childList:true,subtree:true})}
function mount(){styles();removeMapOverlay();views();cards();counters();charts();toasts();new MutationObserver(removeMapOverlay).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
