/* ReliefLink Animation System v2 - animation-only enhancement. */
(function(){'use strict';
const ID='relieflink-animation-system-v2';
function styles(){if(document.getElementById(ID))return;const s=document.createElement('style');s.id=ID;s.textContent=`
:root{--rl-fast:180ms;--rl-motion:260ms}.rl-live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;background:#22c55e;animation:rlPulse 1.8s ease-in-out infinite;vertical-align:middle}.rl-live-dot.offline{background:#ef4444;animation:none}.rl-live-dot.updating{background:#f59e0b}@keyframes rlPulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.38;transform:scale(.78)}}
.rl-disaster-marker-host{background:transparent!important;border:0!important}.rl-disaster-marker{display:block;width:18px;height:18px;border-radius:50%;background:var(--rl-marker-color);border:2px solid rgba(255,255,255,.95);box-shadow:0 2px 8px rgba(0,0,0,.28);position:relative;animation:rlMarkerBeat 1.9s ease-in-out infinite}.rl-disaster-marker:after{content:"";position:absolute;inset:-5px;border:2px solid var(--rl-marker-color);border-radius:50%;opacity:0;animation:rlRing 2.2s ease-out infinite}.rl-disaster-marker.critical{animation-duration:1.25s}.rl-disaster-marker.critical:after{animation-duration:1.5s}@keyframes rlMarkerBeat{0%,100%{transform:scale(.9)}50%{transform:scale(1.08)}}@keyframes rlRing{0%{transform:scale(.65);opacity:.7}75%,100%{transform:scale(1.8);opacity:0}}
.rl-page-enter{animation:rlPage .28s cubic-bezier(.2,.7,.2,1) both}.rl-card-enter{animation:rlCard .42s cubic-bezier(.2,.7,.2,1) both}.rl-toast-enter{animation:rlToast .22s ease-out both}.rl-critical-alert{animation:rlAlert .42s cubic-bezier(.2,.7,.2,1) both}@keyframes rlPage{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@keyframes rlCard{from{opacity:0;transform:translateY(9px) scale(.99)}to{opacity:1;transform:none}}@keyframes rlToast{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}@keyframes rlAlert{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:none}}
.rl-live-truth-card{transition:transform .18s ease,box-shadow .18s ease}.rl-live-truth-card:hover{transform:translateY(-2px);box-shadow:0 8px 22px rgba(15,23,42,.1)}.rl-notification-new{animation:rlBell .52s ease-in-out}.rl-chart-enter{animation:rlChart .85s ease-out both}.rl-counter{font-variant-numeric:tabular-nums}@keyframes rlBell{0%,100%{transform:rotate(0)}15%{transform:rotate(-8deg)}30%{transform:rotate(8deg)}45%{transform:rotate(-5deg)}60%{transform:rotate(5deg)}}@keyframes rlChart{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
button,.btn,.nav-item,.sidebar-item,a.card,.card,.stat-card,.metric-card{transition:transform .18s ease,box-shadow .18s ease,opacity .18s ease}.nav-item:hover,.sidebar-item:hover{transform:translateX(3px)}button:not(:disabled):active,.btn:not(:disabled):active{transform:scale(.98)}.stat-card:hover,.metric-card:hover{transform:translateY(-2px)}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}.rl-disaster-marker:after{display:none}}
`;document.head.appendChild(s)}
function liveStatus(){if(document.getElementById('rl-live-status'))return;const map=document.querySelector('#disaster-map-element');if(!map)return;const e=document.createElement('div');e.id='rl-live-status';e.style.cssText='position:absolute;z-index:1000;top:10px;left:10px;padding:6px 9px;border-radius:8px;background:rgba(255,255,255,.92);box-shadow:0 2px 8px rgba(0,0,0,.12);font-size:12px';e.innerHTML='<span class="rl-live-dot"></span><b>LIVE</b> · Connecting…';map.parentElement?.appendChild(e)}
function views(){const app=document.querySelector('#app');if(!app)return;let last=null;new MutationObserver(()=>{const a=app.querySelectorAll('main,.main-content,.content-area,.dashboard-content,.view-content,.page-content,.content-panel');const el=a[a.length-1];if(el&&el!==last){last=el;el.classList.remove('rl-page-enter');void el.offsetWidth;el.classList.add('rl-page-enter')}}).observe(app,{childList:true,subtree:true})}
function cards(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('.card,.stat-card,.metric-card,.dashboard-card,.panel').forEach((el,i)=>{if(!el.dataset.rlAnim){el.dataset.rlAnim='1';el.classList.add('rl-card-enter');el.style.animationDelay=Math.min(i*35,280)+'ms'}})).observe(app,{childList:true,subtree:true})}
function counters(){const app=document.querySelector('#app');if(!app)return;const animate=()=>app.querySelectorAll('[data-count],.stat-value,.metric-value,.kpi-value').forEach(el=>{if(el.dataset.rlCounter)return;const m=(el.textContent||'').trim().match(/^([\d,]+)(.*)$/);if(!m)return;const target=Number(m[1].replace(/,/g,''));if(!Number.isFinite(target)||target>10000000)return;el.dataset.rlCounter='1';const suffix=m[2],t0=performance.now();const tick=t=>{const p=Math.min(1,(t-t0)/650),v=Math.round(target*(1-Math.pow(1-p,3)));el.textContent=v.toLocaleString()+suffix;if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});animate();new MutationObserver(()=>requestAnimationFrame(animate)).observe(app,{childList:true,subtree:true})}
function charts(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('canvas').forEach(c=>{if(!c.dataset.rlChart){c.dataset.rlChart='1';c.classList.add('rl-chart-enter')}})).observe(app,{childList:true,subtree:true})}
function toasts(){const app=document.querySelector('#app');if(!app)return;new MutationObserver(()=>app.querySelectorAll('.toast,.notification,.alert-toast,[role="alert"]').forEach(x=>x.classList.add('rl-toast-enter'))).observe(app,{childList:true,subtree:true})}
function mount(){styles();liveStatus();views();cards();counters();charts();toasts()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
