/* ReliefLink Animation System v1 - visual polish only. */
(function(){
'use strict';
const STYLE_ID='relieflink-animation-system-v1';
function installStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
:root{--rl-motion-fast:180ms;--rl-motion:240ms;--rl-motion-slow:700ms}
.rl-live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:6px;background:#22c55e;animation:rlLivePulse 1.8s ease-in-out infinite;vertical-align:middle}.rl-live-dot.updating{background:#f59e0b}.rl-live-dot.offline{background:#ef4444;animation:none}
@keyframes rlLivePulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.42;transform:scale(.78)}}
.rl-live-marker{position:relative;border-radius:50%;will-change:transform}.rl-live-marker:after{content:"";position:absolute;inset:-5px;border:2px solid currentColor;border-radius:50%;opacity:0;animation:rlMarkerPulse 2.2s ease-out infinite}.rl-live-marker.critical:after{animation-duration:1.65s}.rl-live-marker.high:after{animation-duration:2s}
@keyframes rlMarkerPulse{0%{transform:scale(.72);opacity:.65}70%,100%{transform:scale(1.65);opacity:0}}
.rl-page-enter{animation:rlPageIn var(--rl-motion) cubic-bezier(.2,.7,.2,1) both}.rl-card-enter{animation:rlCardIn 420ms cubic-bezier(.2,.7,.2,1) both}.rl-toast-enter{animation:rlToastIn 220ms ease-out both}.rl-toast-exit{animation:rlToastOut 180ms ease-in both}
@keyframes rlPageIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}@keyframes rlCardIn{from{opacity:0;transform:translateY(8px) scale(.99)}to{opacity:1;transform:none}}@keyframes rlToastIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes rlToastOut{from{opacity:1;transform:none}to{opacity:0;transform:translateY(8px)}}
.rl-critical-alert{animation:rlAlertIn 420ms cubic-bezier(.2,.7,.2,1) both}.rl-critical-alert.new{box-shadow:0 0 0 0 rgba(239,68,68,.2);animation:rlAlertIn 420ms cubic-bezier(.2,.7,.2,1) both,rlAlertGlow 1.8s ease-out 1}
@keyframes rlAlertIn{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:none}}@keyframes rlAlertGlow{0%{box-shadow:0 0 0 0 rgba(239,68,68,.28)}100%{box-shadow:0 0 0 12px rgba(239,68,68,0)}}
.rl-notification-new{animation:rlBellShake 520ms ease-in-out both}@keyframes rlBellShake{0%,100%{transform:rotate(0)}15%{transform:rotate(-8deg)}30%{transform:rotate(8deg)}45%{transform:rotate(-5deg)}60%{transform:rotate(5deg)}75%{transform:rotate(-2deg)}}
.rl-counter{font-variant-numeric:tabular-nums}.rl-chart-enter{animation:rlChartIn 850ms ease-out both}@keyframes rlChartIn{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
.rl-source-badge{display:inline-flex;align-items:center;gap:5px;padding:3px 7px;border-radius:999px;background:rgba(100,116,139,.09);font-size:.66rem;font-weight:700}.rl-updated-status{font-size:.68rem;color:#64748b}.rl-live-truth-card{transition:transform 180ms ease,box-shadow 180ms ease}.rl-live-truth-card:hover{transform:translateY(-2px);box-shadow:0 7px 20px rgba(15,23,42,.09)}
@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.001ms!important}.rl-live-marker:after{display:none}}
`;
document.head.appendChild(s)}
function addLiveStatus(){if(document.getElementById('rl-live-status'))return;const map=document.querySelector('#disaster-map-element');if(!map)return;const host=map.parentElement||map;const el=document.createElement('div');el.id='rl-live-status';el.className='rl-updated-status';el.innerHTML='<span class="rl-live-dot"></span><b>LIVE</b> · Initializing live feeds…';host.insertBefore(el,map);}
function pageTransitions(){const app=document.querySelector('#app');if(!app)return;let last='';const observer=new MutationObserver(()=>{const main=app.querySelector('main,.main-content,.content-area,.dashboard-content,[class*="view"]');if(main&&main!==last){last=main;main.classList.remove('rl-page-enter');void main.offsetWidth;main.classList.add('rl-page-enter')}});observer.observe(app,{childList:true,subtree:true});}
function animateCounters(){const els=document.querySelectorAll('[data-count],.stat-value,.metric-value,.kpi-value');els.forEach(el=>{if(el.dataset.rlAnimated)return;const raw=(el.textContent||'').trim();const m=raw.match(/(-?\d[\d,]*)(.*)$/);if(!m)return;const target=parseInt(m[1].replace(/,/g,''),10);if(!Number.isFinite(target)||target>10000000)return;el.dataset.rlAnimated='1';el.classList.add('rl-counter');let start=0;const t0=performance.now();const tick=t=>{const p=Math.min(1,(t-t0)/700);const eased=1-Math.pow(1-p,3);el.textContent=Math.round(start+(target-start)*eased).toLocaleString()+m[2];if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)})}
function observeCounters(){animateCounters();const ob=new MutationObserver(()=>requestAnimationFrame(animateCounters));const root=document.querySelector('#app');if(root)ob.observe(root,{childList:true,subtree:true,characterData:true})}
function patchToasts(){const original=window.showToast;if(typeof original!=='function'||original.__rlWrapped)return;const wrapped=function(){const result=original.apply(this,arguments);setTimeout(()=>{document.querySelectorAll('.toast,.notification,.alert-toast,[role="alert"]').forEach(x=>x.classList.add('rl-toast-enter'))},0);return result};wrapped.__rlWrapped=true;window.showToast=wrapped}
function mount(){installStyles();addLiveStatus();pageTransitions();observeCounters();patchToasts();setInterval(()=>{const status=document.querySelector('#rl-live-status');if(status&&!status.textContent.includes('offline')){const d=new Date();status.innerHTML='<span class="rl-live-dot"></span><b>LIVE</b> · Updated '+d.toLocaleTimeString() }},60000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
